//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::comments::Entity as Comments;
pub use super::post_tags::Entity as PostTags;
pub use super::posts::Entity as Posts;
pub use super::tags::Entity as Tags;
