//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::comments::Entity as Comments;
pub use super::posts::Entity as Posts;
pub use super::posttags::Entity as Posttags;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
