version: '3'

services:
  postgres: 
    image: postgres:14
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plainlyrusty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: plainlyrusty_postgres
    ports:
      - "5432:5432"
