version: '3'

services:
  postgres: 
    image: postgres:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plainlyrusty
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
    container_name: plailyrusty_postgres
    ports:
      - "5432:5432"
