version: '3'

services:
  postgres: 
    image: postgres:14
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plainlyrusty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    container_name: plainlyrusty_postgres
  app:
    image: plainlyrusty:${IMAGE_VERSION}
    environment:
      - TZ=Asia/Shanghai
      - RUST_LOG=${RUST_LOG}
      - CONFIG_FILE=/mnt/${CONFIG_FILE}
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../configs:/mnt/configs
    depends_on:
      - postgres
    container_name: plainlyrusty_app