[application]
address = "127.0.0.1:8000"
url = "http://127.0.0.1:8000"
debug = true
owner_github_name = "octocat"

[graphql]
endpoint = "/"

[database]
url = "DATABASE_URL"

[oauth_github]
client_id = "CLIENT_ID"
client_secret = "CLIENT_SECRET"
user_agent = "plainly-rusty/0"

[rss_channel]
title = ""
description = ""
copyright = ""
