[application]
address = "127.0.0.1:8000"
graphql_endpoint = "/"
debug = true

[graphql]
endpoint = "/"

[database]
url = "DATABASE_URL"

[oauth_github]
client_id = "CLIENT_ID"
client_secret = "CLIENT_SECRET"
